# Generated by Django 4.0.4 on 2022-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='role'),
        ),
    ]
