# Generated by Django 4.0.4 on 2022-08-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
