# Generated by Django 4.0.4 on 2022-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='company'),
        ),
    ]
