# Generated by Django 4.0.4 on 2022-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_remove_recruiter_vacancy'),
        ('vacancies', '0003_vacancy_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='students',
            field=models.ManyToManyField(related_name='vacancies', to='oauth.student', verbose_name='students'),
        ),
    ]
