# Generated by Django 4.0.4 on 2022-06-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_remove_recruiter_vacancy'),
        ('vacancies', '0004_vacancy_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='vacancies', to='oauth.student', verbose_name='students'),
        ),
    ]
