# Generated by Django 4.0.4 on 2022-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_remove_recruiter_vacancy'),
        ('vacancies', '0006_alter_vacancy_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='students',
            field=models.ManyToManyField(blank=True, to='oauth.student'),
        ),
    ]
