# Generated by Django 4.0.4 on 2022-08-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_vacancy_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contact'),
        ),
    ]
